### ISSUE TITLE
Not working with geometry nodes in blender 3.4 on MacOS 12.6

### ISSUE THREAD

**Issue by nurb2kea** [strike-digital/node_pie#5] opened 2022-10-24 11:29 UTC
Hi,

just noticed that the last versions/builds of blender 3.4 on macOS 12.6 is not showing the Pie for Geometry nodes.
![Screen Shot 2022-10-24 at 1 12 19 pm](https://user-images.githubusercontent.com/57676085/197513814-3c7f940a-14a1-4895-8d9a-55582633df97.jpg)
![Screen Shot 2022-10-24 at 1 15 49 pm](https://user-images.githubusercontent.com/57676085/197513843-264198e0-feea-40db-b0ac-7e80f27e0f2b.jpg)

In blender 3.3.1 on macOS 12.6 it is working...
![Screen Shot 2022-10-24 at 1 22 18 pm](https://user-images.githubusercontent.com/57676085/197515495-fe14bf80-aa30-4f86-8842-1f9069455305.jpg)

Just to let you know, because blender 3.5 alpha comes on the 26 Oct. 2022 and MacOS Ventura today on the 24 Oct.

Thanks in Advance :-)

**Comment by strike-digital** [comment] 2022-10-24 13:41
Hi, unfortunately, this is due to an intentional regression in the API, that currently, I have no way of working around :(
To help with adding assets to the node editor, the devs have removed functionality from the `nodeitems_utils` API, which the addon relies on to get the lists of nodes and their categories.

I've made a post about this on Devtalk, but unfortunately, it doesn't seem as if this will be fixed before the 3.4 release, as the devs haven't replied to my concerns...
https://devtalk.blender.org/t/nodeitems-utils-module-deprecated-in-3-4-with-no-obvious-alternative/26158?u=strike_digital

if you wanted, it would probably help if others commented in the thread to boost its visibility a bit, because otherwise, it looks like the addon will simply have to stay broken in 3.4+

Sorry for the bad news, but I'm really not sure that there's a good option available to replace it currently :(

**Comment by strike-digital** [comment] 2022-11-05 22:06
Ok, I've fixed this using an annoying hack, the latest version should work in 3.4 :)

**Comment by nurb2kea** [comment] 2022-11-06 00:21
WOHOO !! 👍 
You are a champ my friend. Works like a charme in all node editors.
Thank you very much for your work and support. 
It's so nice, just in the morning I checked if there is some progress & in the afternoon (for me) you fixed and uploaded it.

**Comment by strike-digital** [comment] 2022-11-06 11:49
Perfect, glad it's working, that's really nice to hear :)

**Closed by strike-digital** 2022-11-06 11:49 UTC
