### ISSUE TITLE
Errors & not saving with version 1.2.3 & 1.2.4 $ 1.2.5 on macos 13

### ISSUE THREAD

**Issue by nurb2kea** [strike-digital/node_pie#8] opened 2022-11-08 15:23 UTC
Hi, 

just tried version 1.2.4 and got the following errors and then tried version 1.2.3 with the same result + not saving the shortcut keys changed in preferences for both.

Then I went back to 1.2.2 and having No errors,
But the saving of the shortcut keys also fails.

Blender 3.5
![System](https://user-images.githubusercontent.com/57676085/200604119-ca7a6b4c-615a-49ed-a0cd-4b323079d2ee.jpg)

![Screenshot 2022-11-08 at 4 03 56 pm](https://user-images.githubusercontent.com/57676085/200603408-80aad9d0-f9d0-45a0-93cc-7bbd62a826ec.jpg)

![Screenshot 2022-11-08 at 4 04 41 pm](https://user-images.githubusercontent.com/57676085/200603257-b5d7a3cd-1ba3-4b97-8864-c6d897dff154.jpg)

![Screenshot 2022-11-08 at 3 59 47 pm](https://user-images.githubusercontent.com/57676085/200603693-3ebd3b0b-ba79-4e0e-9715-62e701ee95d6.jpg)
![Screenshot 2022-11-08 at 4 00 09 pm](https://user-images.githubusercontent.com/57676085/200603732-09c5d803-f85b-4ee7-8990-b1ac19ce7546.jpg)
![Screenshot 2022-11-08 at 4 03 01 pm](https://user-images.githubusercontent.com/57676085/200603755-0f11c1a6-f2d8-4c22-ba40-d977684cf609.jpg)
![Screenshot 2022-11-08 at 4 08 51 pm](https://user-images.githubusercontent.com/57676085/200603770-1669299c-76cb-4333-b418-747c0d68c557.jpg)
![Screenshot 2022-11-08 at 4 09 15 pm](https://user-images.githubusercontent.com/57676085/200603781-47efb169-e070-49c4-a8ab-299b56ab0b1e.jpg)

**Comment by nurb2kea** [comment] 2022-11-08 15:41
Same with 1.2.5.
(uninstall, restart, install, restart)

![Screenshot 2022-11-08 at 4 37 24 pm](https://user-images.githubusercontent.com/57676085/200609371-ca43e3e2-ed5a-4be1-aadf-4a360b9b8e8d.jpg)

**Comment by strike-digital** [comment] 2022-11-08 15:47
Ah, thanks for pointing that out, I was doing some experimenting and I forgot to take some of the code out, should be fixed now

**Comment by strike-digital** [comment] 2022-11-08 15:53
It'll now also remember whether the key map is active or not

**Comment by nurb2kea** [comment] 2022-11-08 16:16
Here I have noticed something:
![Screenshot 2022-11-08 at 5 11 23 pm](https://user-images.githubusercontent.com/57676085/200618234-0c5030f0-b357-43a4-b1bf-f665367dab8d.jpg)


That is what's in the keymap.json:

[{"alt": 0, "key_modifier": "NONE", "oskey": 0, "any": false, "shift": 0, "direction": "ANY", "repeat": false, "type": "LEFTMOUSE", "ctrl": 1, "value": "PRESS"}, {"alt": 0, "key_modifier": "NONE", "oskey": 0, "any": false, "shift": 0, "direction": "ANY", "repeat": false, "type": "A", "ctrl": 1, "value": "PRESS"}]

**Comment by nurb2kea** [comment] 2022-11-08 16:26
![Screenshot 2022-11-08 at 5 24 35 pm](https://user-images.githubusercontent.com/57676085/200620633-ef79d908-df82-4244-a66f-1db80f460e18.jpg)

**Comment by nurb2kea** [comment] 2022-11-08 16:36
I'm back in 5 hours for further testing, got some offscreen disruptions to solve :-)

**Comment by strike-digital** [comment] 2022-11-08 19:08
Ah, yeah, the way it works is that when the addon is disabled, it writes the current keymap to the file, and then loads it again when it is enabled again, so it doesn't actually have anything to do with saving the preferences.

Just to clarify, if you change the keybind, disable and then re-enable the addon, does the keybind go back to ctrl-click?

**Comment by nurb2kea** [comment] 2022-11-08 19:24
Your are right, but it's odd.
When I change the keys and save, nothing happens to the keymap.json, BUT when I then disable it , it will save the keymap.json and holding it in this state.
Means it works, but...!!?...you need to write it into the addon so people know how to save it...what is also not the perfect solution.

**Comment by strike-digital** [comment] 2022-11-08 20:22
I'm not sure I understand? It's really meant to be an automatic thing that the user shouldn't have to know about, and as far as I can see, it works quite well?

**Comment by strike-digital** [comment] 2022-11-08 22:41
Ok, there's been a bit of a misunderstanding I think...

What you've described is the addon working as intended:
* When it is enabled, it will read the keymap.json file, and load the keymaps contained in it.
* When it is disabled, it will save the current keymaps to that file, thus saving any changes that have been made.
* This happens automatically every time blender starts and is quit, not when the preferences are saved (it doesn't actually have anything to do with the preferences)

I think it would be easier to ignore the keymaps.json file for now, I think it's just adding to the confusion.

So: If you change one of the key bindings, and then quit blender, does it keep that key binding when you reopen blender again?
I think that's the most important part.

**Comment by nurb2kea** [comment] 2022-11-08 23:04
No, it's not.
(I watch it side by side) Blender app window next to the finder window showing the Applications support forlder with the keymap.json file.)

1.) I change a key and nothing happens to the keymap file and the key binding change ONLY works UNTIL I restart blender !!
2.) It does NOT keep key bindings if I just quit blender after I changed a key.

That's what I tried to say before.

**Comment by strike-digital** [comment] 2022-11-08 23:36
Ah, ok, that is weird, it works on my computer...
Can you try installing this version, and then checking in the terminal once you enable the addon to see if it has printed anything there:
[node_pie_1_2_7.zip](https://github.com/strike-digital/node_pie/files/9965969/node_pie_1_2_7.zip)

**Comment by nurb2kea** [comment] 2022-11-08 23:48
uninstalled old addon and installed 1.2.7
then wehnenabled...
![Screenshot 2022-11-09 at 12 45 40 am](https://user-images.githubusercontent.com/57676085/200700395-0c81f047-8549-4d27-a57b-ed45817a8bf4.jpg)
![Screenshot 2022-11-09 at 12 46 46 am](https://user-images.githubusercontent.com/57676085/200700562-cc1daa8b-30b7-47a7-830c-40f953b23ace.jpg)

**Comment by nurb2kea** [comment] 2022-12-08 21:46
Hi, 

found this helpful git here: https://github.com/JohnKazucki/Blender_Addon-Customizable_Keymaps
Maybe that helps to solve the keymap problem !?

**Comment by strike-digital** [comment] 2023-06-16 16:40
Hi, sorry this took so long, hopefully this should fixed in the latest version.

And thanks for that link, that was actually really helpful!

**Closed** 2023-06-18 11:00 UTC
