### ISSUE TITLE
The material window is not available in blender 4.2 beta

### ISSUE THREAD

**Issue by Cookybear** [strike-digital/node_pie#30] opened 2024-06-14 06:56 UTC
The material window is not available in blender 4.2 beta

**Comment by strike-digital** [comment] 2024-06-15 00:33
Hi, it's not clear what you mean. Can you give a clear description of what the problem is?

**Comment by Cookybear** [comment] 2024-06-15 00:49
![image](https://github.com/strike-digital/node_pie/assets/172749409/3e64204f-0528-4371-8672-904769637cb9)

**Comment by strike-digital** [comment] 2024-06-15 00:51
Hmm that's odd, I can't replicate the problem on my end.

Are you sure you're using the [latest version ](https://github.com/strike-digital/node_pie/releases/tag/1.2.31)(1.2.31)?

**Comment by Cookybear** [comment] 2024-06-15 00:52
Yes, but it can be used in the geometry node interface

**Comment by Cookybear** [comment] 2024-06-15 00:53
![image](https://github.com/strike-digital/node_pie/assets/172749409/f9d409fe-1f2e-4c8d-a9f3-efd8b201ea6b)

**Comment by Cookybear** [comment] 2024-06-15 00:54
I used blender 4.2btea

**Comment by Cookybear** [comment] 2024-06-15 00:57
![image](https://github.com/strike-digital/node_pie/assets/172749409/698acee7-eae3-4bb2-9150-f1a61686370d)

**Comment by HooThat** [comment] 2024-07-17 02:53
I'm running into this issue as well，windows/blender4.2/1.2.31
Unfortunately, this node tree is not supported, as it doesn't use the standard node api. You can define the pie menu for this node tree manually by enabling developer extras in the preferences, and choosing 'Create definition file for this node tree type' from the right click menu in this node editor. 
Be aware that this could require a lot of work, depending on the number of nodes required
![20240717105231](https://github.com/user-attachments/assets/4e3bc46e-733b-4607-af72-d26aefd2a478)

**Comment by strike-digital** [comment] 2024-07-17 17:54
Ah thanks for bumping this, it was caused by the update to Eevee next in 4.2.

I made a new release, and it should be fixed now:  https://github.com/strike-digital/node_pie/releases/tag/1.2.32

**Closed** 2024-07-21 23:57 UTC
